services:
  - type: web
    name: Backend_Registration_Login
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: DB_USERNAME
        value: avnadmin
      - key: JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - key: DB_URL
        value: jdbc:mysql://mysql-3fb39daf-loginpage.d.aivencloud.com:15184/defaultdb?sslMode=REQUIRED&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_PASSWORD
        sync: false



